version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: budget-app-postgres
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./budget-app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget_user -d budget_app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: